"""initial

Revision ID: 7e80f83f816c
Revises: 
Create Date: 2026-07-12 19:43:07.843564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e80f83f816c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_phone_hash'), 'blacklist', ['phone_hash'], unique=True)
    op.create_table('phone_defs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.Integer(), nullable=False),
    sa.Column('range_start', sa.BigInteger(), nullable=False),
    sa.Column('range_end', sa.BigInteger(), nullable=False),
    sa.Column('operator', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_defs_prefix'), 'phone_defs', ['prefix'], unique=False)
    op.create_index(op.f('ix_phone_defs_region'), 'phone_defs', ['region'], unique=False)
    op.create_table('phone_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('count_listings', sa.Integer(), nullable=False),
    sa.Column('count_sources', sa.Integer(), nullable=False),
    sa.Column('regions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('is_agent_manual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_stats_phone_hash'), 'phone_stats', ['phone_hash'], unique=True)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('avito_location_id', sa.Integer(), nullable=True),
    sa.Column('cian_region_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('AVITO', 'CIAN', name='listingsource'), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('metro', sa.String(length=100), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone_raw', sa.String(length=100), nullable=True),
    sa.Column('phone_formatted', sa.String(length=20), nullable=True),
    sa.Column('phone_region', sa.String(length=100), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('is_agent', sa.Boolean(), nullable=False),
    sa.Column('agent_score', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_external_id'), 'listings', ['external_id'], unique=True)
    op.create_index(op.f('ix_listings_is_active'), 'listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_listings_is_agent'), 'listings', ['is_agent'], unique=False)
    op.create_index(op.f('ix_listings_phone_formatted'), 'listings', ['phone_formatted'], unique=False)
    op.create_index(op.f('ix_listings_region_id'), 'listings', ['region_id'], unique=False)
    op.create_index(op.f('ix_listings_source'), 'listings', ['source'], unique=False)
    op.create_table('parse_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('listings_found', sa.Integer(), nullable=False),
    sa.Column('listings_new', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_tasks')
    op.drop_index(op.f('ix_listings_source'), table_name='listings')
    op.drop_index(op.f('ix_listings_region_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_phone_formatted'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_agent'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_active'), table_name='listings')
    op.drop_index(op.f('ix_listings_external_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('regions')
    op.drop_index(op.f('ix_phone_stats_phone_hash'), table_name='phone_stats')
    op.drop_table('phone_stats')
    op.drop_index(op.f('ix_phone_defs_region'), table_name='phone_defs')
    op.drop_index(op.f('ix_phone_defs_prefix'), table_name='phone_defs')
    op.drop_table('phone_defs')
    op.drop_index(op.f('ix_blacklist_phone_hash'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
